name: mix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      MIX_ENV: test

    services:
      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025
          - 8025:8025
        env:
          options: >-
            --health-cmd nc -zw3 localhost 1025
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    strategy:
      # https://hexdocs.pm/elixir/compatibility-and-deprecations.html#between-elixir-and-erlang-otp
      matrix:
        elixir: [1.16, 1.15, 1.14, 1.13]
        otp: [26, 25, 24, 23]
        include:
          # TODO
          - elixir: v1.17.0-rc.0
            otp: 27
        exclude:
          - elixir: 1.15
            otp: 23
          - elixir: 1.16
            otp: 23
          - elixir: 1.13
            otp: 26

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-
            test-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}-ref-refs/heads/master-mix-

      - run: mix deps.get --only $MIX_ENV
      - run: mix compile --warnings-as-errors
      - run: mix test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          # TODO
          elixir-version: v1.17.0-rc.0
          otp-version: 27
      - run: mix format --check-formatted
